# Copyright 2026 The precedent authors.
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at http://www.apache.org/licenses/LICENSE-2.0
# SPDX-License-Identifier: Apache-2.0
"""CORRECTION MINER v1 — every correction is a test.

A user correction is free, exogenous, user-labelled policy-violation data, and
the violating action is already on tape.  This module finds them.

What v1 adds over v0
--------------------
* **sentence-level detection** — a turn is split into sentences and each one is
  judged on its own, so "继续执行。还有，你能不能省着点 fable5 用量？" is mined as
  the second sentence, not as a 40-character blob, and the quote stored on the
  candidate is the sentence the user actually corrected with;
* **a question filter** — a sentence that ends in ``？``/``?`` and contains no
  imperative is a question, not a correction ("我们不是做自进化的吗？" is asking,
  "不要用 pip，好吗？" is telling);
* **lookaround guards** — 特别 / 别的 / 是不是 / 不用担心 / 不要紧 must not fire,
  because those characters live inside extremely common non-corrective words;
* **Chinese segmentation** — ``pip install precedent-cli[zh]`` brings jieba and
  the topic tokens become words; without it the tokeniser degrades to character
  bigrams, which is what v0 always did.  :data:`SEGMENTER` says which ran;
* **a revert detector** — ``git revert`` / ``git checkout --`` / ``git restore``
  / ``git reset --hard`` against a file the agent wrote earlier in the same
  session is a correction *without any words at all*, and 撤销 / 回滚 / 恢复 /
  undo / revert in a human turn is one with them;
* **repeated instructions across sessions** — a later turn that restates an
  earlier correction is mined even when it contains no correction word, because
  restating it *is* the signal (the user should not have to say 我说过 twice).

Layered heuristics, one confidence score
----------------------------------------
    (i)   a negation / imperative pattern fires in some sentence.  Strong forms
          ("不要", "别", "don't", "i said") score 0.55; soft ones ("又", "重新",
          "应该", "again") 0.30.  A revert *action* scores 0.50 on its own.
    (ii)  the turn follows an assistant ``tool_use`` (+0.25).  Those calls are
          recorded as the **violating action** the birth gate replays.
    (iii) the topic recurs in >=2 sessions (+0.20), decided after grouping.
    (iv)  the turn is accompanied by a revert of an agent edit (+0.15).
"""

from __future__ import annotations

import hashlib
import os
import re
from dataclasses import dataclass, field

from receipts.transcripts import (SessionData, find_sessions, iter_records,
                                  load_session)

__all__ = [
    "Correction",
    "HumanTurn",
    "MineResult",
    "RevertAction",
    "SEGMENTER",
    "SKIP_PREFIXES",
    "Topic",
    "analyse_text",
    "content_tokens",
    "detect_patterns",
    "detect_reverts",
    "has_imperative",
    "is_question",
    "is_skill_expansion",
    "iter_human_turns",
    "jaccard",
    "load_sessions",
    "mine",
    "split_sentences",
    "strip_code_fences",
    "strip_heredocs",
    "zh_tokens",
]

# --------------------------------------------------------------------------
# 0. optional Chinese segmenter — extras: precedent-cli[zh]
# --------------------------------------------------------------------------

_JIEBA = None
_JIEBA_TRIED = False


def _jieba():
    """Import jieba once, if the ``[zh]`` extra is installed.  Never required."""
    global _JIEBA, _JIEBA_TRIED
    if not _JIEBA_TRIED:
        _JIEBA_TRIED = True
        if os.environ.get("PRECEDENT_NO_JIEBA"):
            _JIEBA = None
        else:
            try:                                          # pragma: no cover - optional
                import jieba                              # type: ignore
                jieba.setLogLevel(60)
                _JIEBA = jieba
            except Exception:
                _JIEBA = None
    return _JIEBA


def segmenter_name() -> str:
    return "jieba" if _jieba() is not None else "bigram"


SEGMENTER = segmenter_name


# --------------------------------------------------------------------------
# 1. human turns
# --------------------------------------------------------------------------

#: A user record whose text starts with one of these is the harness expanding a
#: skill or a slash command into the conversation, not a human speaking.
SKIP_PREFIXES: tuple[str, ...] = (
    "<",
    "Base directory for this skill",
    "# Workflow authoring reference",
    "This session is being continued from a previous conversation",
    "Continue from where you left off",
    "Caveat: The messages below were generated by the user",
)

#: …and anything containing this marker is a slash-command expansion.
SKIP_CONTAINS: tuple[str, ...] = ("<command-message>",)

#: Structural markers of the same thing.
SKIP_MARKER_FIELDS: tuple[str, ...] = ("sourceToolUseID", "turnCompanion", "isMeta",
                                       "isCompactSummary", "isVisibleInTranscriptOnly")

MAX_QUOTE_CHARS = 120
MAX_TOOL_SUMMARY_CHARS = 120
MAX_PRECEDING_TOOLS = 3
#: how far after a fire we look for a confirming correction (temporal gate)
FOLLOW_UP_TURNS = 3


def is_skill_expansion(text: str, rec: dict | None = None) -> bool:
    """True for skill / slash-command / system expansions masquerading as user turns."""
    if rec is not None and not _is_declared_human(rec):
        if any(rec.get(f) for f in SKIP_MARKER_FIELDS):
            return True
    t = (text or "").lstrip()
    if not t:
        return True
    if t.startswith(SKIP_PREFIXES):
        return True
    return any(marker in text for marker in SKIP_CONTAINS)


def _is_declared_human(rec: dict) -> bool:
    origin = rec.get("origin")
    return isinstance(origin, dict) and origin.get("kind") == "human"


def _text_blocks(rec: dict) -> list[str]:
    msg = rec.get("message")
    if not isinstance(msg, dict):
        return []
    c = msg.get("content")
    if isinstance(c, str):
        return [c]
    if isinstance(c, list):
        return [b.get("text") or "" for b in c
                if isinstance(b, dict) and b.get("type") == "text"]
    return []


@dataclass
class HumanTurn:
    session_id: str
    project_slug: str
    transcript: str
    line_no: int
    ts: str | None
    text: str
    index: int = 0                              # nth human turn in the session
    preceding_tools: list[dict] = field(default_factory=list)

    def locator(self) -> str:
        return f"{os.path.basename(self.transcript)}:{self.line_no}"

    def quote(self, limit: int = MAX_QUOTE_CHARS) -> str:
        t = " ".join(self.text.split())
        return t if len(t) <= limit else t[:limit] + "…"


def _tool_summary(name: str, inp: dict) -> str:
    """One-line description of what the agent was doing when it got corrected."""
    if not isinstance(inp, dict):
        return ""
    for key in ("command", "file_path", "notebook_path", "path", "skill",
                "description", "prompt", "script", "scriptPath", "pattern",
                "url", "query"):
        v = inp.get(key)
        if isinstance(v, str) and v.strip():
            s = " ".join(v.split())
            return s if len(s) <= MAX_TOOL_SUMMARY_CHARS else s[:MAX_TOOL_SUMMARY_CHARS] + "…"
    keys = ",".join(sorted(k for k in inp if isinstance(k, str))[:4])
    return f"({keys})" if keys else ""


def iter_human_turns(sess: SessionData) -> list[HumanTurn]:
    """Human turns of one session, each carrying the tool calls it followed."""
    turns: list[HumanTurn] = []
    for line_no, rec in iter_records(sess.path):
        if rec.get("type") != "user":
            continue
        if rec.get("sourceToolAssistantUUID"):
            continue
        origin = rec.get("origin")
        if isinstance(origin, dict):
            kind = origin.get("kind")
            if kind and kind != "human":
                continue        # task-notification, hook, etc. — not the user
        texts = [t for t in _text_blocks(rec) if t and t.strip()]
        if not texts:
            continue            # a tool_result carrier, not a prompt
        text = "\n".join(texts).strip()
        if is_skill_expansion(text, rec):
            continue
        turns.append(HumanTurn(
            session_id=sess.session_id, project_slug=sess.project_slug,
            transcript=sess.path, line_no=line_no, ts=rec.get("timestamp"),
            text=text))

    main_calls = [tc for tc in sess.tool_calls if tc.source == sess.path]
    main_calls.sort(key=lambda t: t.line_no)
    prev_line = 0
    for i, turn in enumerate(turns):
        turn.index = i
        window = [tc for tc in main_calls if prev_line < tc.line_no < turn.line_no]
        window.sort(key=lambda t: -t.line_no)
        turn.preceding_tools = [{
            "tool": tc.name,
            "summary": _tool_summary(tc.name, tc.input),
            "input": tc.input if isinstance(tc.input, dict) else {},
            "lineNo": tc.line_no,
            "ts": tc.ts,
        } for tc in window[:MAX_PRECEDING_TOOLS]]
        prev_line = turn.line_no
    return turns


def load_sessions(claude_home: str, project_filter: str | None = None,
                  last_n: int | None = None,
                  include_subagents: bool = True) -> list[SessionData]:
    """Sessions, oldest first, narrowed by ``--project`` / ``--last`` like receipts."""
    found = find_sessions(claude_home, project_filter)
    sessions = [load_session(slug, path, include_subagents=include_subagents)
                for slug, path in found]
    sessions.sort(key=lambda s: (s.started_at or "", s.session_id))
    if last_n is not None and last_n > 0:
        sessions = sessions[-last_n:]
    return sessions


# --------------------------------------------------------------------------
# 2. sentences, questions, imperatives
# --------------------------------------------------------------------------

#: Chinese enders always split; an ASCII "." splits only when whitespace follows,
#: so ``protected.md`` and ``2.1.268`` survive as single tokens.
_SENT_SPLIT = re.compile(r"(?<=[。！？!?；;\n])|(?<=\.)(?=\s)")

#: Sentence-final question marks.  ``吗``/``呢`` alone are not enough: "别用 pip 吗"
#: is vanishingly rare next to "不要用 pip 吗" as a genuine instruction.
_QUESTION_TAIL = re.compile(r"[？?]\s*$")

#: What makes a question still an instruction.  These are imperative *verbs* and
#: politeness frames, deliberately not the same list as the correction patterns:
#: "你能不能省着点用量？" is a request; "这个不是已经做完了吗？" is not.
_IMPERATIVE = re.compile(
    r"不要|别用|别再|必须|请\s*(?!问)|改用|改成|换成|换掉|记住|以后|下次|永远|"
    r"停下|停止|给我|去做|重新|重做|撤销|回滚|恢复|还原|省着点|省点|少用|注意|"
    r"\bdon['’]?t\b|\bdo not\b|\bnever\b|\bstop\b|\bmust\b|\bplease\b|\balways\b|"
    r"\brevert\b|\bundo\b|\bfix\b|\bremove\b|\bswitch to\b|\bmake sure\b|\binstead\b",
    re.IGNORECASE)


#: ```` ```lang\n … ``` ```` — a pasted log, diff or config.  Whatever is inside
#: is something the user is *showing* the agent, not something they are telling
#: it: a log line that reads "ERROR: don't use pip" is not a correction, and
#: mining it plants a bogus t0 and a bogus quote on the rule compiled from it.
_CODE_FENCE = re.compile(r"^[ \t]*(`{3,}|~{3,})[^\n]*\n.*?(?:^[ \t]*\1[^\n]*$|\Z)",
                         re.DOTALL | re.MULTILINE)


def strip_code_fences(text: str) -> str:
    """Blank out fenced code blocks, keeping the surrounding prose intact.

    Inline ``code`` spans are left alone: a correction very often names its
    subject in one ("不要用 `pip`"), and dropping it would drop the token the
    topic is grouped by.
    """
    return _CODE_FENCE.sub("\n", text or "")


def split_sentences(text: str) -> list[str]:
    """Split on Chinese and ASCII sentence enders, keeping the ender attached."""
    parts = [p.strip() for p in _SENT_SPLIT.split(text or "")]
    return [p for p in parts if p]


def is_question(sentence: str) -> bool:
    return bool(_QUESTION_TAIL.search((sentence or "").strip()))


def has_imperative(sentence: str) -> bool:
    return bool(_IMPERATIVE.search(sentence or ""))


# --------------------------------------------------------------------------
# 3. correction patterns
# --------------------------------------------------------------------------

STRONG = 0.55
WEAK = 0.30
REVERT = 0.50
REPEAT = 0.30

#: An English pattern word immediately followed by ``-``, ``_``, ``/`` or a
#: ``.``-plus-word-character is part of a filename or an identifier, not a
#: sentence: ``dont-touch.md`` / ``stop-server.sh`` / ``revert.py`` / ``undo/``.
_NOT_IDENT = r"(?![-_/]|\.\w)"

#: ``(label, regex, weight)``.  The lookarounds are the whole reason this list
#: is not a one-liner: 别 lives inside 特别/级别/区别/别的, 不是 inside 是不是,
#: 不用 inside 不用担心, 不要 inside 不要紧, 停 inside 不停/马不停蹄.
_PATTERN_SPECS: list[tuple[str, str, float]] = [
    # zh — strong
    ("不要", r"不要(?!紧)", STRONG),
    ("别", r"(?<![特识区级差个分类派性辨告鉴甄送离惜道])别(?![的人墅名称致扭])", STRONG),
    ("不是", r"(?<![是要])不是", STRONG),
    ("不对", r"不对", STRONG),
    ("错了", r"错了|弄错|搞错|错误的", STRONG),
    ("我说过", r"我说过|我说的是|我说了|我不是说|说了多少[次遍]", STRONG),
    ("改用", r"改用|改成", STRONG),
    ("换成", r"换成|换掉|换个|换一个|换别的", STRONG),
    ("不用", r"不用(?!担心|客气|谢|了吧)", STRONG),
    ("停", r"(?<![不马一])停(?:止|下|一下)?", STRONG),
    ("省着点", r"省着点|省一点|少用点|节省点|省点", STRONG),
    ("撤销", r"撤销|撤回|回滚|还原|改回|退回|复原|恢复(?:到|成)?", STRONG),
    # zh — weak (corrective only in context)
    ("又", r"又", WEAK),
    ("重新", r"重新|重来|重做|再来一(?:次|遍|个)", WEAK),
    ("应该", r"应该", WEAK),
    # en — strong.  ``_NOT_IDENT`` keeps "dont-touch.md", "stop-server.sh",
    # "revert.py" and "undo/" from being read as the user saying don't / stop /
    # revert / undo: inside a filename or an identifier the word is a *name*.
    # A sentence-final "stop." still matches — only "stop.py" does not.
    ("don't", r"\bdon['’]?t\b" + _NOT_IDENT, STRONG),
    ("do not", r"\bdo not\b" + _NOT_IDENT, STRONG),
    ("stop", r"\bstop\b" + _NOT_IDENT, STRONG),
    ("instead", r"\binstead\b" + _NOT_IDENT, STRONG),
    ("i said", r"\bi said\b", STRONG),
    ("not that", r"\bnot that\b", STRONG),
    ("wrong", r"\bwrong\b" + _NOT_IDENT, STRONG),
    ("never", r"\bnever\b" + _NOT_IDENT, STRONG),
    ("undo", r"\bundo\b" + _NOT_IDENT, STRONG),
    ("revert", r"(?:\brevert\b" + _NOT_IDENT + r"|\broll(?:ed)?\s+back\b)", STRONG),
    ("shouldn't", r"\bshould(?:n['’]?t| not)\b", STRONG),
    # en — weak
    ("again", r"\bagain\b" + _NOT_IDENT, WEAK),
]

PATTERNS: list[tuple[str, re.Pattern, float]] = [
    (label, re.compile(rx, re.IGNORECASE), w) for label, rx, w in _PATTERN_SPECS
]

_PATTERN_SURFACE_CHARS = set("不要别是对错了我说过又重新做来一次遍改用成换掉个应该停省着点少节弄搞误的担心马"
                             "撤销回滚还原退复恢多")
_PATTERN_SURFACE_WORDS = {
    "dont", "don", "do", "not", "stop", "instead", "i", "said", "that", "wrong",
    "never", "undo", "revert", "shouldnt", "should", "again", "t", "roll", "back",
}


def detect_patterns(text: str) -> list[tuple[str, float]]:
    """Matched ``(label, weight)`` pairs in ``text``, in declaration order.

    Whole-text, no question filter: :func:`analyse_text` is the one that decides
    whether a turn is a correction.
    """
    return [(label, w) for label, rx, w in PATTERNS if rx.search(text)]


@dataclass
class TextAnalysis:
    """Why (or why not) one human turn counts as a correction."""
    is_correction: bool
    sentence: str = ""
    patterns: list[tuple[str, float]] = field(default_factory=list)
    base: float = 0.0
    rejected: list[dict] = field(default_factory=list)   # sentence + reason

    def labels(self) -> list[str]:
        return [p for p, _ in self.patterns]


def analyse_text(text: str) -> TextAnalysis:
    """Sentence-level correction detection with the question filter applied."""
    best: TextAnalysis = TextAnalysis(is_correction=False)
    rejected: list[dict] = []
    for sent in split_sentences(strip_code_fences(text)):
        hits = detect_patterns(sent)
        if not hits:
            continue
        if is_question(sent) and not has_imperative(sent):
            rejected.append({"sentence": sent[:120], "reason": "question",
                             "patterns": [p for p, _ in hits]})
            continue
        base = max(w for _, w in hits)
        if base > best.base:
            best = TextAnalysis(is_correction=True, sentence=sent, patterns=hits,
                                base=base)
    best.rejected = rejected
    return best


# --------------------------------------------------------------------------
# 4. tokenisation + similarity
# --------------------------------------------------------------------------

_URL = re.compile(r"https?://\S+|www\.\S+")
_LATIN = re.compile(r"[A-Za-z0-9][A-Za-z0-9_+.\-]*")
_CJK_RUN = re.compile(r"[一-鿿]+")

EN_STOP = {
    "a", "an", "the", "is", "am", "are", "was", "were", "be", "been", "being",
    "to", "of", "in", "on", "at", "for", "with", "and", "or", "but", "if",
    "it", "its", "this", "these", "those", "there", "here", "then", "than",
    "you", "your", "yours", "we", "our", "us", "me", "my", "mine", "he", "she",
    "they", "them", "their", "please", "can", "could", "would", "will", "shall",
    "may", "might", "just", "now", "also", "very", "so", "as", "by", "from",
    "into", "out", "up", "down", "all", "any", "some", "more", "most", "one",
    "two", "let", "make", "made", "get", "got", "go", "went", "use", "used",
    "using", "did", "does", "doing", "done", "have", "has", "had", "ok", "okay",
    "yes", "no", "what", "why", "how", "when", "where", "who", "which", "about",
} | _PATTERN_SURFACE_WORDS

ZH_STOP_CHARS = set("的了我你他她它是在有和与就都也要会能个这那一不去给来上下过吗呢吧啊把让被很太"
                    "再还又们之于对从但而或及等吧啦嘛哦呀哈么什好可以为所以然后现在需要没有因为但是"
                    "如果已经一些帮给看做把被将其中时候样子啊呢")
ZH_STOP_BIGRAMS = {
    "就是", "可以", "什么", "我们", "你们", "然后", "一下", "这个", "那个", "现在",
    "需要", "没有", "因为", "所以", "但是", "如果", "已经", "一些", "帮我", "给我",
    "怎么", "这样", "那样", "之类", "一个", "是不", "不是", "能不", "不能", "的话",
    "了吗", "好了", "可不", "看一", "一看", "东西", "时候", "问题", "全部", "所有",
    "继续", "一次", "一遍", "这些", "那些", "还是", "或者", "以及", "然而", "而且",
    "去做", "做一", "有没", "没有", "一起", "下来", "出来", "起来", "上去", "过来",
}
ZH_STOP_WORDS = {
    "我们", "你们", "他们", "这个", "那个", "什么", "怎么", "为什么", "现在", "然后",
    "但是", "如果", "已经", "一些", "东西", "时候", "问题", "全部", "所有", "继续",
    "一下", "一次", "一遍", "这样", "那样", "可以", "需要", "没有", "因为", "所以",
    "还是", "或者", "以及", "而且", "起来", "出来", "下来", "自己", "这些", "那些",
    "帮我", "给我", "一个", "就是", "知道", "看看", "先", "再", "都", "很", "太",
}


def zh_tokens(run: str) -> list[str]:
    """Tokenise a Chinese run: jieba words when the ``[zh]`` extra is present,
    character bigrams otherwise.  Both paths are deterministic."""
    jb = _jieba()
    if jb is not None:                                    # pragma: no cover - optional
        out = []
        for w in jb.cut(run, cut_all=False):
            w = w.strip()
            if len(w) >= 2 and w not in ZH_STOP_WORDS:
                if not all(c in ZH_STOP_CHARS or c in _PATTERN_SURFACE_CHARS for c in w):
                    out.append(w)
        return out
    if len(run) == 1:
        if run not in ZH_STOP_CHARS and run not in _PATTERN_SURFACE_CHARS:
            return [run]
        return []
    out = []
    for i in range(len(run) - 1):
        bg = run[i:i + 2]
        if bg in ZH_STOP_BIGRAMS:
            continue
        if all(c in ZH_STOP_CHARS or c in _PATTERN_SURFACE_CHARS for c in bg):
            continue
        out.append(bg)
    return out


def content_tokens(text: str) -> set[str]:
    """Deterministic content-token set: lowercased latin words + Chinese tokens."""
    t = _URL.sub(" ", text or "")
    out: set[str] = set()
    for m in _LATIN.finditer(t):
        w = m.group(0).lower().strip("._-+")
        if len(w) >= 2 and w not in EN_STOP and any(c.isalpha() for c in w):
            out.add(w)
    for run in _CJK_RUN.findall(t):
        out.update(zh_tokens(run))
    return out


def jaccard(a: set[str], b: set[str]) -> float:
    if not a or not b:
        return 0.0
    inter = len(a & b)
    if not inter:
        return 0.0
    return inter / len(a | b)


DEFAULT_SIMILARITY = 0.15
#: a later turn must look *this* much like an earlier correction to be mined as
#: a repeat on its own (no correction word required)
REPEAT_SIMILARITY = 0.34
MIN_REPEAT_TOKENS = 3


# --------------------------------------------------------------------------
# 5. revert detection
# --------------------------------------------------------------------------

_REVERT_CMD = re.compile(
    r"(?i)(?:\A|[\n;&|]|&&|\|\|)\s*git\s+"
    r"(?:revert\b|restore\b|checkout\s+(?:--|HEAD|[0-9a-f]{7,40}\s+--)|"
    r"reset\s+--hard\b|stash\s+(?:pop|drop)\b)")
_PATH_IN_CMD = re.compile(r"[^\s\"']*/[^\s\"';|&]+")
#: ``cat > x <<'EOF' … EOF`` — the body is *data being written*, not commands.
#: Without this a test file that merely contains the string "git checkout --"
#: is mined as a revert (observed on this machine, 4 false positives).
_HEREDOC = re.compile(r"<<-?\s*(['\"]?)([A-Za-z_][A-Za-z0-9_]*)\1"
                      r"(?P<body>.*?)(?:^|\n)\s*\2(?=\s|$)", re.DOTALL)


def strip_heredocs(command: str) -> str:
    """Blank out heredoc bodies so their contents are not read as commands."""
    return _HEREDOC.sub(lambda m: m.group(0)[:m.start("body") - m.start()],
                        command or "")


@dataclass
class RevertAction:
    """A ``git revert``/``restore``/``checkout --`` that undoes an agent edit."""
    session_id: str
    line_no: int
    ts: str | None
    command: str
    source: str
    reverted_paths: list[str] = field(default_factory=list)
    undoes_agent_edit: bool = False

    def to_dict(self) -> dict:
        return {"sessionId": self.session_id, "lineNo": self.line_no, "ts": self.ts,
                "command": self.command[:160], "revertedPaths": self.reverted_paths[:5],
                "undoesAgentEdit": self.undoes_agent_edit,
                "locator": f"{os.path.basename(self.source)}:{self.line_no}"}


def _agent_written_paths(sess: SessionData) -> set[str]:
    out: set[str] = set()
    for tc in sess.tool_calls:
        if tc.name in ("Write", "Edit", "MultiEdit", "NotebookEdit"):
            inp = tc.input if isinstance(tc.input, dict) else {}
            for key in ("file_path", "notebook_path"):
                v = inp.get(key)
                if isinstance(v, str) and v:
                    out.add(v)
                    out.add(os.path.basename(v))
    return out


def detect_reverts(sess: SessionData) -> list[RevertAction]:
    """``git revert``/``restore``/``checkout --``/``reset --hard`` in this session.

    ``undoes_agent_edit`` is True when the command names a file the agent wrote
    or edited earlier in the same session — the strongest correction signal
    there is, because the user did not even have to type a sentence.

    Only the **main** transcript is read: a subagent running ``git checkout``
    is the agent tidying up after itself, not the user undoing the agent.  And
    heredoc bodies are blanked first, because a command that *writes a file
    containing* ``git checkout --`` is not a revert.
    """
    written = _agent_written_paths(sess)
    out: list[RevertAction] = []
    for tc in sorted(sess.tool_calls, key=lambda t: (t.ts or "", t.line_no)):
        if tc.name != "Bash" or tc.source != sess.path:
            continue
        inp = tc.input if isinstance(tc.input, dict) else {}
        cmd = inp.get("command")
        if not isinstance(cmd, str):
            continue
        scrubbed = strip_heredocs(cmd)
        if not _REVERT_CMD.search(scrubbed):
            continue
        cmd = scrubbed
        paths = [p for p in _PATH_IN_CMD.findall(cmd)][:8]
        hit = [p for p in paths
               if p in written or os.path.basename(p) in written]
        bare = [w for w in re.findall(r"[\w./\-]+", cmd)
                if w in written or os.path.basename(w) in written]
        out.append(RevertAction(
            session_id=sess.session_id, line_no=tc.line_no, ts=tc.ts,
            command=" ".join(cmd.split()), source=tc.source,
            reverted_paths=sorted(dict.fromkeys(hit + bare))[:5],
            undoes_agent_edit=bool(hit or bare)))
    return out


# --------------------------------------------------------------------------
# 6. corrections + topics
# --------------------------------------------------------------------------

@dataclass
class Correction:
    turn: HumanTurn
    patterns: list[tuple[str, float]]
    base: float
    follows_tool: bool
    repeated: bool = False
    tokens: set[str] = field(default_factory=set)
    sentence: str = ""
    signals: list[str] = field(default_factory=list)
    reverts: list[RevertAction] = field(default_factory=list)
    rejected_sentences: list[dict] = field(default_factory=list)

    @property
    def confidence(self) -> float:
        c = self.base
        if self.follows_tool:
            c += 0.25
        if self.repeated:
            c += 0.20
        if self.reverts:
            c += 0.15
        return round(min(1.0, c), 3)

    def quote(self, limit: int = MAX_QUOTE_CHARS) -> str:
        """The *sentence* the user corrected with, not the whole turn."""
        s = " ".join((self.sentence or self.turn.text).split())
        return s if len(s) <= limit else s[:limit] + "…"

    def to_dict(self) -> dict:
        t = self.turn
        return {
            "sessionId": t.session_id,
            "projectSlug": t.project_slug,
            "locator": t.locator(),
            "transcript": t.transcript,
            "lineNo": t.line_no,
            "turnIndex": t.index,
            "ts": t.ts,
            "quote": self.quote(),
            "turnQuote": t.quote(),
            "patterns": [p for p, _ in self.patterns],
            "signals": self.signals,
            "followsToolUse": self.follows_tool,
            "repeated": self.repeated,
            "confidence": self.confidence,
            "precedingTools": [{k: v for k, v in tool.items() if k != "input"}
                               for tool in t.preceding_tools],
            "reverts": [r.to_dict() for r in self.reverts],
            "rejectedSentences": self.rejected_sentences,
        }


@dataclass
class Topic:
    id: str
    members: list[Correction] = field(default_factory=list)
    label: str = ""
    written_in: list[dict] = field(default_factory=list)
    auto: dict | None = None            # auto-compiled candidate + gate verdict

    @property
    def sessions(self) -> list[str]:
        seen: list[str] = []
        for c in self.members:
            if c.turn.session_id not in seen:
                seen.append(c.turn.session_id)
        return seen

    @property
    def count(self) -> int:
        return len(self.members)

    @property
    def repeated(self) -> bool:
        return len(self.sessions) >= 2

    @property
    def t0(self) -> str | None:
        """The earliest correction time in the topic — the policy's birth date."""
        stamps = sorted(c.turn.ts for c in self.members if c.turn.ts)
        return stamps[0] if stamps else None

    def top_tokens(self, n: int = 8) -> list[str]:
        freq: dict[str, int] = {}
        for c in self.members:
            for tok in c.tokens:
                freq[tok] = freq.get(tok, 0) + 1
        return [tok for tok, _ in sorted(freq.items(),
                                          key=lambda kv: (-kv[1], kv[0]))[:n]]

    def preceding_tools(self) -> list[dict]:
        out: list[dict] = []
        for c in self.members:
            for tool in c.turn.preceding_tools:
                out.append(dict(tool, sessionId=c.turn.session_id,
                                locator=c.turn.locator()))
        return out

    def to_dict(self) -> dict:
        from .compile import suggest_check          # local import: avoids a cycle
        d = {
            "id": self.id,
            "label": self.label,
            "count": self.count,
            "sessions": self.sessions,
            "nSessions": len(self.sessions),
            "repeated": self.repeated,
            "t0": self.t0,
            "maxConfidence": max((c.confidence for c in self.members), default=0.0),
            "topTokens": self.top_tokens(),
            "quotes": [c.quote() for c in self.members[:5]],
            "corrections": [c.to_dict() for c in self.members],
            "precedingTools": [{k: v for k, v in t.items() if k != "input"}
                               for t in self.preceding_tools()[:10]],
            "writtenIn": self.written_in,
            "suggestedCheck": suggest_check(self),
        }
        if self.auto is not None:
            d["autoCompiled"] = self.auto
        return d


def _topic_id(first: Correction) -> str:
    key = f"{first.turn.session_id}:{first.turn.line_no}"
    return "t-" + hashlib.sha256(key.encode("utf-8")).hexdigest()[:8]


def _group(corrections: list[Correction], similarity: float) -> list[Topic]:
    """Deterministic single-link clustering by max Jaccard to any member."""
    topics: list[Topic] = []
    for c in corrections:
        best_idx, best_sim = -1, 0.0
        for i, t in enumerate(topics):
            sim = max(jaccard(c.tokens, m.tokens) for m in t.members)
            if sim >= similarity and sim > best_sim:
                best_idx, best_sim = i, sim
        if best_idx >= 0:
            topics[best_idx].members.append(c)
        else:
            topics.append(Topic(id="", members=[c]))
    for t in topics:
        t.id = _topic_id(t.members[0])
        t.label = " ".join(t.top_tokens(5)) or t.members[0].quote(40)
    return topics


# --------------------------------------------------------------------------
# 7. "written but violated"
# --------------------------------------------------------------------------

def _memory_texts(claude_home: str, sessions: list[SessionData]) -> list[tuple[str, str]]:
    """``(display name, normalised text)`` for every CLAUDE.md / memory / rule file."""
    from receipts.artifacts import discover_artifacts

    slugs: list[str] = []
    cwds: dict[str, str | None] = {}
    for s in sessions:
        if s.project_slug not in cwds:
            slugs.append(s.project_slug)
        if s.cwd and not cwds.get(s.project_slug):
            cwds[s.project_slug] = s.cwd
        cwds.setdefault(s.project_slug, None)
    out: list[tuple[str, str]] = []
    for art in discover_artifacts(claude_home, slugs, cwds):
        if art.kind not in ("memory", "memory_index", "claude_md", "rule"):
            continue
        text = art.content or ""
        if not text.strip():
            continue
        out.append((f"{art.name} ({art.kind})", text.lower()))
    return out


MIN_TOKENS_FOR_WRITTEN = 2


def _mark_written(topics: list[Topic], texts: list[tuple[str, str]]) -> None:
    for t in topics:
        toks = [tok for tok in t.top_tokens(6) if len(tok) >= 2]
        if len(toks) < MIN_TOKENS_FOR_WRITTEN:
            continue
        for name, body in texts:
            hit = [tok for tok in toks if tok in body]
            if len(hit) >= MIN_TOKENS_FOR_WRITTEN:
                t.written_in.append({"artifact": name, "matchedTokens": hit})


# --------------------------------------------------------------------------
# 8. the miner
# --------------------------------------------------------------------------

@dataclass
class MineResult:
    claude_home: str
    generated_at: str
    project_filter: str | None
    last_n: int | None
    similarity: float
    sessions: list[SessionData] = field(default_factory=list)
    n_sessions: int = 0
    n_human_turns: int = 0
    n_skipped_expansions: int = 0
    n_questions_filtered: int = 0
    corrections: list[Correction] = field(default_factory=list)
    topics: list[Topic] = field(default_factory=list)
    reverts: list[RevertAction] = field(default_factory=list)
    turns_by_session: dict[str, list[HumanTurn]] = field(default_factory=dict)
    segmenter: str = "bigram"

    @property
    def n_corrections(self) -> int:
        return len(self.corrections)

    @property
    def pct_corrections(self) -> float:
        if not self.n_human_turns:
            return 0.0
        return round(100.0 * self.n_corrections / self.n_human_turns, 1)

    @property
    def repeated_topics(self) -> list[Topic]:
        return [t for t in self.topics if t.repeated]

    @property
    def written_but_violated(self) -> list[Topic]:
        return [t for t in self.topics if t.written_in]

    def topic(self, topic_id: str) -> Topic | None:
        tid = (topic_id or "").strip()
        for t in self.topics:
            if t.id == tid:
                return t
        m = re.fullmatch(r"[Tt](\d+)", tid)
        if m:
            i = int(m.group(1)) - 1
            ordered = self.ordered_topics()
            if 0 <= i < len(ordered):
                return ordered[i]
        return None

    def topics_for(self, spec: str) -> list[Topic]:
        """``"t-aaa,T3"`` -> the topics it names.  Raises ``KeyError`` on a miss."""
        out: list[Topic] = []
        for part in str(spec or "").replace(" ", "").split(","):
            if not part:
                continue
            t = self.topic(part)
            if t is None:
                raise KeyError(part)
            if t not in out:
                out.append(t)
        return out

    def ordered_topics(self) -> list[Topic]:
        """Most interesting first: repeated, then frequent, then confident."""
        return sorted(self.topics,
                      key=lambda t: (-int(t.repeated), -len(t.sessions), -t.count,
                                     -max((c.confidence for c in t.members), default=0.0),
                                     t.id))

    def to_dict(self) -> dict:
        from . import SCHEMA_VERSION, __version__
        ordered = self.ordered_topics()
        n_auto = len([t for t in self.topics if t.auto])
        n_pass = len([t for t in self.topics
                      if t.auto and t.auto.get("gate", {}).get("verdict") == "PASS"])
        return {
            "schemaVersion": SCHEMA_VERSION,
            "tool": {"name": "precedent", "version": __version__},
            "mine": {
                "claudeHome": self.claude_home,
                "generatedAt": self.generated_at,
                "projectFilter": self.project_filter,
                "lastN": self.last_n,
                "similarity": self.similarity,
                "segmenter": self.segmenter,
                "nSessions": self.n_sessions,
                "nHumanTurns": self.n_human_turns,
                "nSkippedExpansions": self.n_skipped_expansions,
                "nQuestionsFiltered": self.n_questions_filtered,
                "nCorrections": self.n_corrections,
                "pctCorrections": self.pct_corrections,
                "nTopics": len(self.topics),
                "nRepeatedTopics": len(self.repeated_topics),
                "nWrittenButViolated": len(self.written_but_violated),
                "nReverts": len(self.reverts),
                "nAutoCompiled": n_auto,
                "nAutoPass": n_pass,
                "readOnly": True,
            },
            "topics": [dict(t.to_dict(), index=f"T{i + 1}")
                       for i, t in enumerate(ordered)],
            "reverts": [r.to_dict() for r in self.reverts],
            "limitations": limitations(self),
        }


def limitations(result: MineResult) -> list[str]:
    lim = [
        "A correction is detected by surface pattern, never by a model. A turn "
        "that corrects the agent without any of the listed words is missed "
        "(false negative), and a turn that merely quotes one can be a false "
        "positive — the confidence score, not a boolean, is the honest output.",
        f"Chinese is tokenised with {result.segmenter}"
        + ("" if result.segmenter == "jieba" else
           " (character bigrams; `pip install precedent-cli[zh]` swaps in jieba)")
        + f"; the similarity threshold ({result.similarity}) is a tunable, not a truth.",
        "The question filter drops a sentence that ends in ？/? and carries no "
        f"imperative ({result.n_questions_filtered} dropped here). A question "
        "that is really an order phrased politely without any imperative word is "
        "therefore missed.",
        "\"Written but violated\" is substring/keyword matching against "
        "CLAUDE.md / memory / rule files. It shows the topic's words are in the "
        "file; it does not prove the file was loaded in the session where the "
        "correction happened (run `precedent scan` for that).",
        "Only the main transcript is read for human turns; a subagent has no "
        "human in it. Tool calls from subagents are still counted as recorded "
        "actions by the temporal birth gate.",
    ]
    if result.last_n or result.project_filter:
        lim.append("`--last` / `--project` narrow the session set, so every count "
                   "here is relative to the scanned sessions, not the whole machine.")
    return lim


def mine(claude_home: str, project_filter: str | None = None,
         last_n: int | None = None, similarity: float = DEFAULT_SIMILARITY,
         sessions: list[SessionData] | None = None,
         now_iso_str: str | None = None) -> MineResult:
    """Walk human turns, detect corrections, group them into topics."""
    from .state import now_iso

    home = os.path.realpath(os.path.expanduser(claude_home))
    sessions = sessions if sessions is not None else load_sessions(
        home, project_filter, last_n)
    result = MineResult(
        claude_home=home, generated_at=now_iso_str or now_iso(),
        project_filter=project_filter, last_n=last_n, similarity=similarity,
        sessions=sessions, n_sessions=len(sessions), segmenter=segmenter_name())

    corrections: list[Correction] = []
    non_corrections: list[HumanTurn] = []
    for sess in sessions:
        result.n_skipped_expansions += _count_expansions(sess)
        reverts = detect_reverts(sess)
        result.reverts.extend(reverts)
        turns = iter_human_turns(sess)
        result.turns_by_session[sess.session_id] = turns
        for turn in turns:
            result.n_human_turns += 1
            got = analyse_text(turn.text)
            result.n_questions_filtered += len(got.rejected)
            attached = _reverts_for_turn(turn, turns, reverts)
            if not got.is_correction:
                if attached:
                    # (iv) a revert of an agent edit is a correction with no words
                    corrections.append(Correction(
                        turn=turn, patterns=[("revert-action", REVERT)], base=REVERT,
                        follows_tool=bool(turn.preceding_tools),
                        tokens=content_tokens(turn.text) | {
                            os.path.basename(p) for r in attached
                            for p in r.reverted_paths},
                        sentence=turn.quote(), signals=["revert-action"],
                        reverts=attached, rejected_sentences=got.rejected))
                else:
                    non_corrections.append(turn)
                continue
            signals = ["pattern"]
            if attached:
                signals.append("revert-action")
            corrections.append(Correction(
                turn=turn, patterns=got.patterns, base=got.base,
                follows_tool=bool(turn.preceding_tools),
                tokens=content_tokens(got.sentence or turn.text),
                sentence=got.sentence, signals=signals, reverts=attached,
                rejected_sentences=got.rejected))

    # (v) repeated instructions across sessions — no correction word required
    corrections.extend(_repeat_across_sessions(corrections, non_corrections))

    corrections.sort(key=lambda c: (c.turn.ts or "", c.turn.session_id, c.turn.line_no))
    result.corrections = corrections
    result.topics = _group(corrections, similarity)

    for t in result.topics:
        if t.repeated:
            for c in t.members:
                c.repeated = True
                if "repeated-topic" not in c.signals:
                    c.signals.append("repeated-topic")

    _mark_written(result.topics, _memory_texts(home, sessions))
    return result


def _reverts_for_turn(turn: HumanTurn, turns: list[HumanTurn],
                      reverts: list[RevertAction]) -> list[RevertAction]:
    """Reverts that happened between the previous human turn and this one.

    Ordering is by timestamp, not line number: a line number is only comparable
    within one transcript file.
    """
    prev_ts = ""
    for t in turns:
        if t.line_no >= turn.line_no:
            break
        prev_ts = t.ts or prev_ts
    this_ts = turn.ts or ""
    if not this_ts:
        return []
    return [r for r in reverts
            if r.undoes_agent_edit and r.ts and prev_ts < r.ts < this_ts]


def _repeat_across_sessions(corrections: list[Correction],
                            others: list[HumanTurn]) -> list[Correction]:
    """Turns that restate an earlier correction from a *different* session.

    The user should not have to type 我说过 for the miner to notice that this is
    the third time they have asked for the same thing.
    """
    out: list[Correction] = []
    for turn in others:
        toks = content_tokens(turn.text)
        if len(toks) < MIN_REPEAT_TOKENS:
            continue
        best = None
        for c in corrections:
            if c.turn.session_id == turn.session_id:
                continue
            if (c.turn.ts or "") >= (turn.ts or ""):
                continue               # only a *later* restatement counts
            sim = jaccard(toks, c.tokens)
            if sim >= REPEAT_SIMILARITY and (best is None or sim > best[0]):
                best = (sim, c)
        if best is None:
            continue
        sim, src = best
        out.append(Correction(
            turn=turn, patterns=[("repeat-across-sessions", REPEAT)], base=REPEAT,
            follows_tool=bool(turn.preceding_tools), tokens=toks,
            sentence=turn.quote(), signals=["repeat-across-sessions"],
            rejected_sentences=[{"sentence": src.quote(60),
                                 "reason": f"restates {src.turn.session_id[:8]} "
                                           f"(jaccard {sim:.2f})",
                                 "patterns": []}]))
    return out


def _count_expansions(sess: SessionData) -> int:
    """How many user records the skip-list removed — reported, never hidden."""
    n = 0
    for _line_no, rec in iter_records(sess.path):
        if rec.get("type") != "user" or rec.get("sourceToolAssistantUUID"):
            continue
        origin = rec.get("origin")
        if isinstance(origin, dict) and origin.get("kind") and origin.get("kind") != "human":
            continue
        texts = [t for t in _text_blocks(rec) if t and t.strip()]
        if texts and is_skill_expansion("\n".join(texts).strip(), rec):
            n += 1
    return n


def write_topics(state, result: MineResult) -> str:
    """Persist the mined topics so ``precedent compile`` can address them."""
    payload = result.to_dict()
    return state.write_json(os.path.join(state.root, "topics.json"), payload)


def load_topics(state) -> dict | None:
    data = state.read_json(os.path.join(state.root, "topics.json"))
    return data if isinstance(data, dict) else None
